package controller;

/**
 * Created by Alexander on 23.02.2016.
 */
public enum CommandName {

    FIND_FILM_BY_ID,
    FIND_FILM_BY_TITLE,
    FIND_FILM_BY_DATE,
    GET_FILMS_COLLECTION,
    ADD_NEW_FILM,
    UPDATE_FILM,
    REMOVE_FILM,

    GET_USERS_COLLECTION,
    GET_USER_BY_ID,
    REG_USER,
    UPDATE_USER,
    REMOVE_USER,

    GET_SEANCES_COLLECTION,
    GET_SEANCES_BY_DATE,
    GET_SEANCE_BY_ID,
    UPDATE_SEANCE
}
