package controller;

/**
 * Created by Alexander on 23.02.2016.
 */
public enum CommandName {
    //User
    LOGIN_USER,
    LOGOUT_USER,
    REGISTRATION_USER,
    FIND_USER_BY_ID,
    FIND_USER_BY_LOGIN,

    //Seance
    GET_TODAY_SEANCES,


    //Film
    FIND_FILM_BY_ID,
    FIND_FILM_BY_TITLE,
    FIND_FILM_BY_DATE,
    GET_FILMS_COLLECTION,

    ADD_NEW_FILM,
    UPDATE_FILM,
    REMOVE_FILM,




    GET_USERS_COLLECTION,
    GET_USER_BY_ID,
    UPDATE_USER,
    REMOVE_USER,

    GET_SEANCES_COLLECTION,
    GET_SEANCES_BY_DATE,
    GET_SEANCE_BY_ID,
    UPDATE_SEANCE,
    ADD_NEW_SEANCE,
    ADD_SEANCE_FORM,
    REMOVE_SEANCE,

    GET_TICKETS_COLLECTION,
    FIND_TICKET_BY_ID,
    REMOVE_TICKET
}
